import { Media } from '../common/media';
import { RoleEnum } from '../role/role-enum';

export interface User {
  id: string;
  document: string;
  typeDocument: string;
  enable: boolean;
  isTemporalPassword: boolean;
  token: string;
  names: string;
  lastNames: string;
  customer: string;
  phone: string;
  role: string[];
  email: string;
  creationUserId: string;
  creationDate: string;
  modificationUser: string;
  modificationDate: string;
  modificationUserId: string;
  newUser: boolean;
  enabled?: boolean;
  roleEnums: RoleEnum[];
  emails: string[];
  documentId: string;
  typeDocumentId: string;
  profilePhotoPath: string;
  profilePhotoBase64: string;
  state: string;
  userType: string | null;
  idConnection: string;
  description: string;
  username: string | null;
  password: string | null;
  idTypeUser: string | null;
  files: any | null;
  roles: any | null;
  lastConnection: string;
  lastModifiedDate: string;
  departmentRootName: string;
  clientName: string;
  idDepartment: string;
  idClient: string;
  fullName: string;
  isDepartment: boolean;
  idAdminUsers: string | null;
  profileImageFile: Media | null;
  cropImageFile: Media | null;
  patchName: string | null;
  messagePending: any | null;
  isSupervisor: boolean;
}
